# Generated by Django 4.1.1 on 2022-09-13 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("thumb", models.ImageField(upload_to="thumb_courses")),
                ("description", models.TextField(max_length=1000)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CS", "Computer Science"),
                            ("PYTHON", "Python"),
                            ("WEB", "Web"),
                            ("JAVASCRIPT", "JavaScript"),
                            ("AI", "Artificial Intelligence"),
                            ("GD", "Game Development"),
                            ("MAD", "Mobile App Development"),
                        ],
                        max_length=30,
                    ),
                ),
                ("views", models.IntegerField(default=0)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
