# Generated by Django 4.1.1 on 2022-09-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='open_courses',
            new_name='viewed_courses',
        ),
    ]
